version: '3.1'

services:

  postgres-db-container:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgresondockeruser
      POSTGRES_PASSWORD: postgresondockerpassword
      POSTGRES_DB: energyDB

  frontend-and-backend-container:
    image: frontend_and_backend
    restart: always
    ports:
      - 3000:3000

  # instantiate a container that will allow to
  # manage the database through a web interface
  adminer-database-management:
    image: adminer
    restart: always
    ports:
      - 8080:8080
