version: '3.1'

services:
  postgres-db-container:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:?err}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?err}
      POSTGRES_DB: ${POSTGRES_DB:?err}
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./docs/EnergyDB.sql:/docker-entrypoint-initdb.d/EnergyDB.sql

  frontend-and-backend-container:
    image: frontend_and_backend
    restart: always
    ports:
      - 3000:3000
      - 5000:5000

  # instantiate a container that will allow to
  # manage the database through a web interface
  adminer-database-management:
    image: adminer
    restart: always
    ports:
      - 8080:8080
