name: BSU Energy Dashboard CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
    - name: run build.sh
      uses: actions/checkout@v2
    - run: |
        echo "====================[ BUILDING ]===================="
        ./gradlew build
        npm --prefix ./client
        npm --prefix ./client run build
        echo "====================[ TESTING ]====================="
        npm --prefix ./client t --silent -- --watchAll=false


#   test:
#     runs-on: ubuntu-latest
#     steps:
#     - name: run test.sh
#       uses: actions/checkout@v2
#     - run: |
#         npm --prefix ./client t --silent -- --watchAll=false
