name: BSU Energy Dashboard CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build backend
      run: ./gradlew build
    - name: Build frontend
      run: |
        npm --prefix ./client install
        npm --prefix ./client run build


  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Test frontend
      run: |
        npm --prefix ./client install
        npm --prefix ./client test --silent -- --watchAll=false
