name: BSU Energy Dashboard CI
on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'docs/**'
      - 'CONTRIBUTORS'
      - 'LICENSE'
      - '**.md'

  pull_request:
    branches: [ main ]
    paths-ignore:
      - 'docs/**'
      - 'CONTRIBUTORS'
      - 'LICENSE'
      - '**.md'
    
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: build
      run: ./build.sh
    - name: test
      run: ./test.sh

